name: Release Charts

on:
  workflow_dispatch:
    name:
      description: 'Person to greet'
      required: true
      default: "mwang2016"
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Fetch history
        run: git fetch --prune --unshallow

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.4.1

      - uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Add dependency chart repos
        run: |
          helm repo add my-helm-charts https://mwang2016.github.io/my-helm-charts

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.2.1
        with:
          charts_repo_url: "https://mwang2016.github.io/my-helm-charts"
        env:
          CR_TOKEN: "${{ secrets.CR_TOKEN }}"
